# Entry point for lexer package
from .lexer import *

if __name__ == "__main__":
    # temporary test source code
    source_code = [
        'a-',
        'cwass Manji() ',
        'fwunc manji-Manji() ',
        # 'fwunc manji+Class() ',
        # 'manji+Class() ',
        # 'cwass Manji+Manji() ',
        # 'manji+manji() ',
        # 'Manji+manji() ',
        # '   var-Manji = Manji()~',
        # '   Manji()~',
        # '   func()----5~]]'
        # r'pwint("hello \"hello\"")',
        # 'pwint("hello \|hello\|")',
        # 'fwunc 1bc-chan() ',
        # 'fwunc 1bc-chan ',
        # 'fwunc 1bc() ',
        # 'fwunc 1bc ',
        # 'cwass 1bc-chan() ',
        # 'cwass 1bc-chan ',
        # 'cwass 1bc() ',
        # 'cwass 1bc ',
        # 'aqua-chan = func()----5 ',
        # 'fwunc Vtuber() fwunc Vtuber-san() ',
        # 'Vtuber(aqua-Vtuber)~aqua-Vtuber = Vtuber() ',
        # 'aqua-Vtuber=1-2 ',
        # 'aqua.property+(1+2) aqua-Vtuber=1-2~',
        # 'Vtuber.method()-Vtuber.property~',
        # 'Vtuber.uwuwuwu()~',
        # 'vtuber.uwuwuwu()~',
        # 'channel-chan()~',
        # 'channel',
        # '"im an string unterminated string"',
        # '>//< this',
        # 'is',
        # 'a',
        # 'multiline',
        # 'comment',
        # '>//<',
        # 'fwunc channelchan(aqua-Vtuber)',
        # 'fwunc channel()',
        # 'fwunc channel-chan[()',
        # 'channel-chan()',
        # 'chan~',
        # 'chan',
        # 'channel',
        # '  21aqua-chan~',
        # '21aqua-chan~',
        # 'aqua6-chan = "AKUA AISHITEEE!"~',
        # '"unclosed string',
        # '|what am I|a"~',
        # r'"hello |wo_rld| hello\|world"~ "hello\world|what|is this\|\|\|"~',
        # 'manji-senpai = "foo |aqua7 + shion| foo |ojou| boo"~',
        # '00010000000000000 + 5~',
        # '(1.0, 2.10, 3.)',
        # '1.1.1~',
        # '1.111111111111110000000~',
        # '1111111111111111.1~',
        # '0.00~',
        # '1.~',
        # '8.00~',
        # '9.01~',
        # '6.0',
        # 'fwunc func-type()',
        # 'fwunc Class-type()',
        # "fwunc Class-type() ",
        # "fwunc func-type ",
        # "fwunc Class-type ",
        # "fwunc func() ",
        # "fwunc Class() ",
        # "fwunc func ",
        # "fwunc Class ",
        # "cwass Class() ",
        # "cwass Class-type() ",
        # "cwass Class-type ",
        # "cwass Class ",
        # "cwass func-type() ",
        # "cwass func() ",
        # "cwass func-type ",
        # "cwass func ",
        # "func() ",
        # "Class() ",
        # "Class ",
        # "func-type() ",
        # "func-type ",
        # "Class-type() ",
        # "Class-type ",
        # 'bweak~',
        # ' aqua-chan',
        # 'cwass ',
        # 'aqua-chan = cap~',
        # 'cwass~ bweak',
        # 'dono ',
        # 'do whiwe(',
        # 'donee~',
        # 'ewse iwf(',
        # 'ewse(',
        # 'iwf(',
        # 'minato-chan~ojou~',
        # 'pwint (',
        # 'fax,',
        # 'fow',
        # 'gwobaw',
        # 'inpwt(',
        # 'float-kun = 10.5~',
        # # 'mainuwu-',
        # 'nuww,',
        # 'san~',
        # 'sama ',
        # 'senpai~',
        # 'staart!',
        # 'whiwe (',
        # 'wetuwn(',
    ]
    print_lex(source_code)